using System.Runtime.Serialization;

namespace OpenWeatherMap.Web.Models
{
    public enum DataLanguage
    {
        [EnumMember(Value = "af")] Afrikaans,
        [EnumMember(Value = "al")] Albanian,
        [EnumMember(Value = "ar")] Arabic,
        [EnumMember(Value = "az")] Azerbaijani,
        [EnumMember(Value = "bg")] Bulgarian,
        [EnumMember(Value = "ca")] Catalan,
        [EnumMember(Value = "cz")] Czech,
        [EnumMember(Value = "da")] Danish,
        [EnumMember(Value = "de")] German,
        [EnumMember(Value = "el")] Greek,
        [EnumMember(Value = "en")] English,
        [EnumMember(Value = "eu")] Basque,
        [EnumMember(Value = "fa")] Persian,
        [EnumMember(Value = "fi")] Finnish,
        [EnumMember(Value = "fr")] French,
        [EnumMember(Value = "gl")] Galician,
        [EnumMember(Value = "he")] Hebrew,
        [EnumMember(Value = "hi")] Hindi,
        [EnumMember(Value = "hr")] Croatian,
        [EnumMember(Value = "hu")] Hungarian,
        [EnumMember(Value = "id")] Indonesian,
        [EnumMember(Value = "it")] Italian,
        [EnumMember(Value = "ja")] Japanese,
        [EnumMember(Value = "kr")] Korean,
        [EnumMember(Value = "la")] Latvian,
        [EnumMember(Value = "lt")] Lithuanian,
        [EnumMember(Value = "mk")] Macedonian,
        [EnumMember(Value = "no")] Norwegian,
        [EnumMember(Value = "nl")] Dutch,
        [EnumMember(Value = "pl")] Polish,
        [EnumMember(Value = "pt")] Portuguese,
        [EnumMember(Value = "pt_br")] Português_Brasil,
        [EnumMember(Value = "ro")] Romanian,
        [EnumMember(Value = "ru")] Russian,
        [EnumMember(Value = "sv")] Swedish,
        [EnumMember(Value = "sk")] Slovak,
        [EnumMember(Value = "sl")] Slovenian,
        [EnumMember(Value = "es")] Spanish,
        [EnumMember(Value = "sr")] Serbian,
        [EnumMember(Value = "th")] Thai,
        [EnumMember(Value = "tr")] Turkish,
        [EnumMember(Value = "ua")] Ukrainian,
        [EnumMember(Value = "vi")] Vietnamese,
        [EnumMember(Value = "zh_cn")] Chinese_Simplified,
        [EnumMember(Value = "zh_tw")] Chinese_Traditional,
        [EnumMember(Value = "zu")] Zulu
    }
}
